### ISSUE TITLE
프론트엔드 UI 

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#10]
![웹 1920 – 1](https://user-images.githubusercontent.com/74997333/137095437-8b5d3e5b-06f8-4dd6-9dbe-0d6900a48efb.png)
![웹 1920 - 2](https://user-images.githubusercontent.com/74997333/137095927-10839bd8-f171-40cb-be9d-32913612c7d1.PNG)

기본적인 사용자 인터페이스에 관련된 화면 예시로 공유합니다.
혹시나 추가하고 싶거나 수정하고 싶은 부분 있으면 말씀해주세요.

**Comment by rhdenro** [comment]
저기 좌석이 전체 좌석 보기 선택하면 나오는 화면 인가요?

**Comment by BaekJae** [comment]
좌석 정보를 보는 것이 해당 이미지를 클릭하면 좌석의 정보가 표시되는 방식인가요?

**Comment by jaejin28** [comment]
@BaekJae 전체 좌석보기와 사용가능 좌석 보기 카테고리를 통해 좌석 데이터를 볼 수 있고, 해당 좌석의 정보와 같이 제공되는 좌석의 대표적인 이미지를 누르면 볼 수 있도록 구현 생각중입니다.

**Comment by jaejin28** [comment]
@rhdenro 위의 5개의 카테고리 창은 화면에 계속 노출되고 각 카테고리를 클릭하면 해당 데이터들이 보여집니다.
