### ISSUE TITLE
데이터베이스 모델링

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#11]
데이터베이스 모델링에 대한 설명입니다.

**좌석 테이블**은 아래와 같은 칼럼을 가집니다.
좌석 위치 - 문자열
좌석 번호 - 문자열(Primary Key) -> 중복 불가 ->  Join Key
좌석 사용 가능 여부 - 0,1(boolean)
PC유무 - 0,1(boolean)
콘센트 유무 - 0,1(boolean)
좌석 분류 - 문자열

**좌석 이용 로그 테이블**은 아래와 같은 칼럼을 가집니다. (필요 시에만 Join합니다.)
좌석 번호 - 문자열(Primary Key) -> 중복 불가 -> Join Key
이용 시작 시간 - 문자열('yyyy/mm/dd hh:mm:ss') 형식
이용 종료 시간 - 문자열('yyyy/mm/dd hh:mm:ss') 형식

**사용자 테이블**은 아래와 같은 칼럼을 가집니다.
이름 -문자열
학번 - 문자열(Primary Key)
비밀번호 - 문자열(단방향 암호화 해쉬)
과거 이용 기록 - 문자열(좌석 번호와 같은 형식, 이를 이용하여 Join)
예약 기록 - 문자열

**예약 기록 테이블**은 아래와 같은 칼럼을 가집니다. -> 예약 종료 시 삭제
예약 기록 id - 숫자(Primary Key)
예약자 이름 - 문자열
연장 가능 횟수 - 숫자

추가 의견 있을 시 comment부탁드립니다.

**Comment by rhdenro** [comment]
최초 데이터 요소 반영 다 되어있으니 이걸로 결정하고 추후에 데이터 추가되면 데이터베이스 모델링 다시 논의 하면 될 것 같습니다

**Comment by BaekJae** [comment]
@rhdenro
확인했습니다. DB모델링은 실 서비스 제공 이전까지는 수정 가능하니 언제든지 자유롭게 말씀 부탁드립니다.

**Comment by jaejin28** [comment]
넵
