### ISSUE TITLE
UseCase Diagram

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#12]
Use-case Diagram입니다. 검토 후 comment 부탁드립니다.

![image](https://user-images.githubusercontent.com/29000892/137097115-e06bbef5-4948-405f-81d8-35f5278bec40.png)

**Comment by rhdenro** [comment]
확인했고 요구사항 분석서에 반영 하겠습니다

**Comment by BaekJae** [comment]
@rhdenro 
확인했습니다.

**Comment by jaejin28** [comment]
확인했습니다.
