### ISSUE TITLE
이벨평가 방안

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#13]
<좌석 평가 방법>

기본 규칙 : 사용자의 저장된 좌석 데이터에 대한 별점과 방금 사용한 좌석 데이터의 별점을 비교하여 별점이 낮은 데이터를 제거하는 방식.

추가 규칙 : 좌석에 대한 별점 데이터가 쌓이고 비슷해지면 별점이 같은 데이터중 가장 오래된 데이터를 삭제.

-> 위의 2가지 규칙에 대한 사용자의 만족이 낮다면 사용자가 직접 자신의 데이터를 관리하고 회원가입 시와 동일하게 모든 좌석의 사진을 통해 재선택 하는 방안을 고려.

**Comment by BaekJae** [comment]
해당 방식은 evaluation method이기 보다는 아무래도 자체 내부 처리 로직으로 보일 가능성이 높아 보입니다.
차라리 현재 있는 도서관 어플과의 비교를 하는 방식의 설문조사는 어떨까요?

**Comment by rhdenro** [comment]
발표후 comment받고 결정하는 것이 좋을 것 같습니다

**Comment by jaejin28** [comment]
넵
