### ISSUE TITLE
데이터 베이스 추가 목록

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#14]
데이터 베이스에 추가적으로 인접자리 번호를 넣을 수 있는 string라벨을 하나 더 추가 해 주실수 있습니까?

**Comment by BaekJae** [comment]
확인했습니다. 인접 몇 자리까지 필요하실까요? 
예를 들면, H08좌석이라 하면 H06~10(앞 두 자리, 뒤 두 자리) 정도라 생각하시고 답변 부탁드립니다.

**Comment by rhdenro** [comment]
가장 많이 들어가는 자리는 좌우 마주보는 자리 정도로 생각해서 3개 자리정도로 생각하시면 될 것 같습니다 자리마다 다를 수 있기 때문에 3개 정도의 좌석번호가 들어갈 크기로 설정 하시면 될 것 같습니다

**Comment by BaekJae** [comment]
본인 기준 네 방향 한 개씩 말씀하시는 게 맞으면 진행하겠습니다.

**Comment by jaejin28** [comment]
확인했습니다.
