### ISSUE TITLE
요구사항 분석서 정의서 확인

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#15]
올려놓은 문서들 확인하고 이상있으면 알려주세요

**Comment by BaekJae** [comment]
확인했고 이상 없습니다. 변동사항 반영 위해서 해당 issue는 계속 Open 상태로 유지하는 편이 나을 것 같습니다

**Comment by jaejin28** [comment]
확인했습니다. 이상 없는거 같습니다!
