### ISSUE TITLE
다음 멘토링 질문(10/18)

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#16]
**트래픽 관리** - 트래픽이 과도하게 서버에 쏠렸을 때, 어떻게 해결할 수 있는가?

**서버 이중화** - Heavy한 작업을 담당하는 서버를 별도로 두고, 메인 서버가 이와 통신하게 하는 방향으로 진행하려 하는데 적절한 방식인가?(서버 사이의 지연 시간을 무시해도 될 만큼 효율성이 있는가?)

추가 질문 있으면 comment로 달아주시고, 기존 질문들에 대한 문제 제기도 comment로 해주시면 감사하겠습니다.

**Comment by rhdenro** [comment]
추가 질문은 따로 없습니다

**Comment by jaejin28** [comment]
추가 질문 없습니다.
