### ISSUE TITLE
이벨평가 방안 변경

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#17]
이벨평가 방안에 대해 교수님의 피드백 결과 수정 및 논의해야 할 부분이 있을거 같습니다.
먼저 저희가 구현하고자 하는 추천 시스템만의 차별성은 명확한 UI와 구체적인 정보 제공 및 개인 취향에 맞는 좌석 추천인데 
저번 회의 때 나온 방법인 설문조사를 통해 기존의 앱과 비교하는 방식으로 이벨 평가를 진행하는 방법이 있습니다. 
저도 이 방법이 최선이라고 생각하는데 이외에 다른 의견있으면 제시해주세요.

**Comment by BaekJae** [comment]
제시하신 방안이 최상의 방법이라 생각됩니다.

**Comment by rhdenro** [comment]
나중에 설문조사 질문사항 논의 하면 될것 같습니다

**Comment by jaejin28** [comment]
네 좋습니다.
