### ISSUE TITLE
도서관 좌석 데이터 초본 확인해 주세요

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#18]
좌석 코드(층수, 유형, 분류코드, 좌석번호)
유형
s=스마트열람
j=조망형
p= pc룸
n=노트북 사용 좌석
분류코드:위치순서
좌석번호: 좌석위치

누락된 요소 있는지 확인 후 알려주세요

**Comment by BaekJae** [comment]
확인했습니다.

**Comment by kwongustj** [comment]
확인했습니다.

**Comment by jaejin28** [comment]
확인했습니다.
