### ISSUE TITLE
운영 서버 구성

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#2]
현행 서버 구성 방안입니다.

**웹 서버**
- Node.js Express 기반 서버 구성
- Front-end는 React와 합쳐서 동시 구현

**인공지능 서버**
- 인공지능 tool이 Python 위주로 제공되기 때문에, Python기반의 Back-end 서버 구성 예정
- 활용 예상 Framework : Django
- Front-end는 없음. 단순한 요청 처리

현재 위와 같은 **이중 서버 체제**입니다.

이유
- Express의 특징으로 오류 발생 시 서버가 종료되어 버림
- 서버가 어느 정도의 부하를 버틸 수 있는지 아직 까지는 계산이 되지 않음

혹시나 해당 방안에 대한 개선 방안이 있다면 말씀 부탁 드립니다.

**Comment by rhdenro** [comment]
현재 팀원중 Django를 확실하게 다룰 수 있는 사람이 없어 Django만으로 서버를 구성하기에는 어려움이 있어 Node.js Express를 사용하여 서버를 구성해야 할 것 습니다.

**Comment by BaekJae** [comment]
@rhdenro 
현행 체제를 유지하자는 말씀이신가요?

**Comment by rhdenro** [comment]
네 맞습니다

**Comment by jaejin28** [comment]
@rhdenro 동의합니다
