### ISSUE TITLE
Django 서버 구현 시기, 데이터 확정 시기

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#20]
현재 Django 서버 개설 이전에 분류기 개설이 완료되면 서버를 개설하려고 합니다.

Django App 내부에 해당 프로그램을 삽입하면 구조 상 수정하기 어려워져서 그렇게 진행하려고 하는데 어떠신가요?

그리고 혹시 DB 연동 때문에 여쭙는데 데이터 확정이 언제 진행될까요..?

**Comment by rhdenro** [comment]
데이터는 확정이 현재 데이터로 확정이 되었고
장고는 3단계에서 좌석형태 필터 구현 후 Django서버 구현 하는 것으로 하겠습니다

**Comment by BaekJae** [comment]
@rhdenro 
확인하였습니다. DB 수정사항 있으면 별도로 Issue 개설하거나 연락 부탁드립니다.

**Comment by jaejin28** [comment]
확인했습니다!!

**Comment by jaejin28** [comment]
이슈 닫겠습니다!!
