### ISSUE TITLE
Front Session 사용

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#21]
현재 로그인이 성공하면 Session에 값을 저장하고 이를 Return하여 구현하는 부분까지는 Express 서버 구현이 완료된 상태입니다.

혹시 Session에 들어가야 하는 별도의 내용이 학번(DB의 Primary key)빼고 들어가야 하는 것이 있는지 첨언 부탁드립니다.

현재는 DB내부 정보 전체를 Session에 저장하여 반환하는 방식으로 처리 중입니다.

**Comment by jaejin28** [comment]
네 확인했습니다. 프론트 작업 시 로그인 성공하면 메인페이지 세션으로 넘어가고, 로그인 실패시에는 다른 세션으로 이동하여 팝업 메시지를 띄우는 작업 진행중입니다.

**Comment by rhdenro** [comment]
이슈 마감하겠습니다
