### ISSUE TITLE
라우팅 규칙

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#22]
기본적인 라우팅
'/': 메인 페이지 로딩
'/db': Database를 Control하는데 사용되는 Route

현재까지의 기본적인 Routing 규칙은 이 정도이며, 추가적인 규칙이 생기면 별도로 업로드 하겠습니다.

RESTful API 기반 호출이기 때문에 사용 시 참고 부탁드립니다.

**링크 오류 시 정상 응답이 돌아오지 않거나 서버가 다운될 수 있기 때문에, 유의 부탁 드립니다.**

**Comment by BaekJae** [comment]
예시입니다.

'localhost:8086/' -> 메인 페이지 호출

'localhost:8086/db/register' -> 회원가입 기능. 받은 파라미터 기준으로 프로그램이 Insert를 수행합니다.

**Comment by jaejin28** [comment]
확인했습니다.

**Comment by rhdenro** [comment]
이슈 close하겠습니다
