### ISSUE TITLE
데이터 처리 규칙

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#23]
Front-end 부분에서 API로 요청을 진행하실 때 참고할 부분이 있어 먼저 말씀 드립니다.

대부분 **정보를 서버로 보내는 과정이나, 보안 정보**가 필요한 부분은 모두 라우터가 **POST**로 처리합니다.
Ex) 회원가입, Login

서버에서 **정보를 가져오거나 페이지를 로딩 하는 과정**에서는 라우터가 모두 **GET**으로 처리합니다.
Ex) 메인 페이지 가져오기, 좌석 정보 가져오기

**대부분 특정 링크를 호출하는 과정에서는 모두 GET으로 처리함을 유의하시기 바랍니다.**

진행 과정 중 질문 있으시면 별도 Issue개설 혹은 개인 문의 부탁 드립니다.

**Comment by jaejin28** [comment]
네 확인했습니다. 추가 의문사항 있으면 이슈로 남기겠습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
