### ISSUE TITLE
ui라이브러리 vs 프레임워크

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#24]
vue 가 코드를 작성하기 쉽고, 생산성도 더 좋지만 react는 자바스크립트의 정적 표현을 사용할 때 편리하고 함수형 프로그래밍 활용이 가능하다고 생각하기에 react를 사용하려고 합니다. 물론 진입 장벽도 높고 실제 배워야 할 부분들이 많지만, 차근차근 공부하면서 진행해보려합니다.

**Comment by rhdenro** [comment]
네 알겠습니다

**Comment by BaekJae** [comment]
확인했습니다.서버와의 통신이 필요하시면 별도 연락 주시면 될듯합니다
