### ISSUE TITLE
모델에 제공해야 되는 값이 정해 졌습니다.

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#25]
모델에 
학번 
우대인원 기능 사용 여부 및 인원
pc사용 유무
콘센트 유무 
가장 자리 선호 유무를 
넘겨 주시면 될것 같습니다.
이외에 필요한 입력값이 있다면 추가적으로 이슈로 알려 드리겠습니다

**Comment by BaekJae** [comment]
확인했습니다

**Comment by jaejin28** [comment]
확인했습니다.
