### ISSUE TITLE
사용자 이용 데이터 추가 계획

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#26]
밀집도를 따로 입력을 받아 사용하는 것이 아니라 사용자 이용기록중 별점별로 차등을 두어 사용 당시의 밀집도와 유사한 값일 경우 점수를 주어 리스트에 추가를 하는 방식을 사용하는 방향으로 구현을 할 것이기 때문에 데이터베이스 사용자 기록에 밀집도를 추가적으로 int형으로 생성을 해주셔야 됩니다

**Comment by BaekJae** [comment]
확인했습니다.

**Comment by jaejin28** [comment]
확인했습니다!!

**Comment by jaejin28** [comment]
이슈 닫겠습니다!!
