### ISSUE TITLE
밀집도 데이터 모델에 값을 넣는 방식 논의를 하려고 합니다

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#29]
밀집도까지 웹에서 받은 값으로 현재 값과 비교를 해서 하기에는 웹에서 받아와야 하는 값이 늘어나는데 앞으로 더 많아 질 가능성이 있어 따로 계산할 알고리즘이 있는 요소는 사용자 사용자 선호 좌석 DB에 추가 하는 방식을 쓰려고 하는데
이에 대한 답변 또는 다른  방식이 있으면 제시해 주세요

**Comment by BaekJae** [comment]
DB의 재구성이 필요하다는 말씀을 하시는건가요?

**Comment by rhdenro** [comment]
네

**Comment by BaekJae** [comment]
재구성 진행 완료하였고 반영했습니다.

**Comment by jaejin28** [comment]
확인했습니다!!

**Comment by jaejin28** [comment]
이슈 클로즈 하겠습니다!!
