### ISSUE TITLE
도서관 데이터

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#3]
현재 도서관 내부의 좌석 데이터와 사용자 데이터를 학교 도서관에 요청하긴 했으나 회신이 오지 않고 있습니다.

데이터 수집에 대해 어떤 기법을 사용할 지 말씀해주시면 감사하겠습니다.

데이터가 정상적으로 수집 되지 않을 경우에는 프로젝트의 주제를 변경해야 할 수도 있을 것 같습니다.

**Comment by rhdenro** [comment]
조금더 기다려 보고 회신이 오지 않는다면 프로젝트 주제 변경보단 좌석데이터는 엑셀이나 엑세스 등으로 수작업으로 만들만한 규모의 데이터이니 직접 만들고 사용자 데이터는 회원가입시 평소 도서관 이용자 신규 이용자 상관없이 따로 데이터를 받는 방식으로 방향을 트는 방법도 괜찮다고 생각합니다

**Comment by BaekJae** [comment]
좌석의 사진 데이터는 어떻게 할까요? 직접 수집할까요?

**Comment by jaejin28** [comment]
학교 도서관에서 도서관 내부의 데이터와 학생 기록을 제공해줄지에 대한 의문이 들긴합니다.
또한 도서관 내부의 좌석 정보에 대한 부분은 홈페이지를 통해 얻을 수 있지만,  학생 기록 데이터는 개인정보가 포함된 부분이므로 답장이 온다고 해도 긍정적으로 올거 같지는 않습니다.
그래도 이번 주까지 기다려보고 연락이 안온다면 학과 교수님께 도움을 요청해보는것도 좋은 방법인거 같습니다.

**Comment by BaekJae** [comment]
@jaejin28 
확인했습니다. 그럼 우선 대기해보고 다시 Comment 남기겠습니다.

**Comment by BaekJae** [comment]
현재까지 메일에 답장이 없습니다.

**Comment by BaekJae** [comment]
@rhdenro @jaejin28 
현재 답장이 없는 것으로 보아 가상 데이터를 구축하는 방안이 맞을 것 같습니다.
검토 해 주시면 날짜 잡고 진행하겠습니다.
