### ISSUE TITLE
프론트 진행 상황

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#30]
현재 로그인과 메인페이지 화면 구현중이고, 12주차 13주차까지 해서 세부적인 기능 구현을 완료할 계획입니다.
기능 구현하면서 css로 건드릴 수 있는 요소들까지 같이 개발 진행하고 있습니다.

**Comment by BaekJae** [comment]
확인했습니다.

**Comment by rhdenro** [comment]
확인했습니다
