### ISSUE TITLE
로그인 페이지 관련 기능 

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#31]
자동 로그인 기능 관련해서 팀원들과 상의하고 싶습니다.
현재 충북대학교 도서관 어플은 자동로그인을 설정하는 기능이 있어 이 부분을 기능 추가할 계획입니다.
자동으로 로그인까지는 아니더라도 아이디(학번), 패스워드(비밀번호)는 자동입력되어 있어 로그인 버튼만 누르면 서비스 이용이 가능할 수 있도록 진행하겠습니다.

**Comment by BaekJae** [comment]
그렇다면 Local에 값을 아예 저장하여 불러오는 방식도 괜찮은 것 같습니다.
아마 자동 입력을 구현한다면 Device어딘가에 값이 저장되어 있다는 건데, 그럼 자동 로그인 구현도 가능해보입니다.

**Comment by rhdenro** [comment]
확인 했습니다
