### ISSUE TITLE
메인페이지 기능 구현

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#32]
디자인적인 부분에 대해서 팀원들과 상의를 해본 결과, 현재 충북대학교 블랙보드 웹 페이지와 비슷한 느낌으로 개발하고 있습니다.
메인페이지의 기능은 저번에 올렸던 대로 카테고리 부분을 따로 만들어 메인 기능(좌석보기, 추천받기, 예약받기, 연장하기 등)을 
선택할 수 있도록 하고 있습니다. 
이 부분은 다음주 화요일(18일)까지 완료한 후 commit 하겠습니다.

**Comment by BaekJae** [comment]
확인했습니다.

**Comment by rhdenro** [comment]
확인 했습니다
