### ISSUE TITLE
가중치를 줄 요소 추가 여부 논의

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#33]
사용자가 좌석 이용 후 입력해주는 별점만으로 가중치를 주는 것이 나중에 별점 5점의 좌석들이 많아질 경우 많은 정확도가 떨어질 것이기 때문에 사용자가 5점을 넣은 좌석을 다시 예약하면 그 횟수를 세어 가중치를 더 주는 방식을 사용 하려고 하는데 이에 대한 의견을 묻고 싶습니다

**Comment by BaekJae** [comment]
그럼 데이터를 갱신하는 과정에서 횟수가 적은 데이터를 밀어내는건가요?

**Comment by jaejin28** [comment]
별점 5점 좌석 중 가장 오래된 좌석이 갱신되는건가요?
