### ISSUE TITLE
모델 추천 리스트에 포함 될 내역 입니다 확인 바랍니다

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#34]
우대 인원 사용 시
각 우대인원 수의 자릿수의 좌석들이 2차원 배열 형식으로 들어가고 내부 배열에 좌석 코드가 인원수 개수로 들어가고 우대 좌석이 없다면 빈 배열이 보내질 것이고
예시: [ [ 코드1,코드2,코드3],[코드 9, 코드10, 코드 11]]
우대 인원 미사용 시
각 좌석에는 현재 각 섹터의 밀집도와 좌석 코드가 들어간 2차원 배열 형식으로 보내질 것 입니다 
예시: [ [코드1, 밀집도1],[코드2, 밀집도2]]

**Comment by BaekJae** [comment]
그렇다면 밀집도가 포함되어 있지 않은 좌석의 경우는, 우대 좌석을 사용했다는 전제 하에 시행하겠습니다.

**Comment by jaejin28** [comment]
네 확인했습니다.
