### ISSUE TITLE
사용자 데이터 갱신 규칙 추가 계획 공유

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#35]
시간이 지나면서 5점 좌석이 많아지면 어느 기점으로 좌석이 고착화가 되는 것을 방지하기 위하여 새로 예약한 데이터의 종료 시점과 비교해 사용자 선호좌석 DB의 값들과 비교해 3주이상 차이가 나면 그 값으로 무조건 적으로 대치하는 것으로 규칙을 추가 하겠습니다 다른 의견이 있으시면 제시해 주세요

**Comment by BaekJae** [comment]
확인했습니다.

**Comment by rhdenro** [comment]
추가로 대치하는 데이터의 별점이 3점 이상일 경우 적용하겠습니다

**Comment by jaejin28** [comment]
그러면 1점이나 2점 좌석에 경우는 자신의 선호좌석 db 리스트에 올리지 않겠다는 말씀이신거죠?
