### ISSUE TITLE
DB 재구성

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#36]
요청에 따라, DB를 재구성했습니다.

기존 예약 로그 DB를 삭제하고 DB를 분할 했습니다.

**시스템 로그 DB(예약 로그 DB)**
해당 DB는 시스템의 예약 요청을 관할하며 내부 내용은 지우지 않습니다.
NOT NULL 항목
reservation_id = 예약 번호(Primary key)
reservation_user = 예약자
seat_code = 예약 좌석 코드
start_time = 이용 시작 시간
end_time = 이용 종료 시간
count = 연장 횟수(MAX 3회)

**이용자 선호 좌석 DB**
해당 DB는 사용자의 선호 좌석을 관리하며, 최대 5개로 제한됩니다.
NOT NULL항목
reservation_id = 예약 번호(Primary Key)
reservation_user = 예약자
seat_code = 예약 좌석 코드
NULL 가능 항목
count = 좌석 이용 횟수
date = 최근 이용 일자
score = 별점
density = 좌석의 이용 당시 밀집도

확인 바랍니다.

**Comment by BaekJae** [comment]
요청 과정에서 변수명 유의 부탁드립니다.

**Comment by rhdenro** [comment]
네 확인 했습니다

**Comment by jaejin28** [comment]
네 유의하겠습니다.
