### ISSUE TITLE
Django와 Express간의 통신 규칙

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#37]
현재 Django와 Express로 서버가 이중화 되어 있기 때문에 서버끼리의 통신을 수행하여야 합니다.

**API CALL**을 이용하여 통신을 진행할 것이고, 총 통신은 **2번** 수행 될 예정입니다.

Request의 특성 상 Response가 오지 않으면 에러가 발생하거나 문제가 발생할 수 있으므로 혹여 보내줄 내용이 없더라도 result내에 success혹은 bool 값이라도 넣어 주시면 감사하겠습니다.

통신이 수행될 내역 
1. 선호 좌석을 받아 오는 통신
2. 사용자 별 선호 좌석 테이블에 데이터를 추가하는 통신

사용자 별 선호 좌석 DB는 Django만이 관리하며, Express는 이에 따른 접근 권한이 없습니다.

추가적인 의견이 있다면 제시 부탁드립니다.

**Comment by rhdenro** [comment]
지금은 추가의견은 없고 추후에 필요한 통신 규칙이 있으면 comment 하겠습니다

**Comment by BaekJae** [comment]
@rhdenro 확인했습니다.

**Comment by jaejin28** [comment]
확인했습니다.
