### ISSUE TITLE
Model 캡슐화 요청

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#38]
Node.js 와 Django간의 API CALL 과정에서 특정 URL로 POST 요청을 진행할 예정입니다.

Django 프레임워크의 동작 과정 상 아마 캡슐화를 하여 함수를 URL에 매핑해야 할 것으로 알고있습니다.

현재 올라온 모델로 볼 때 매핑을 진행할 함수가 없는데 매핑을 진행할 함수를 만들어 주시면 감사하겠습니다.

**Comment by rhdenro** [comment]
네 알겠습니다

**Comment by jaejin28** [comment]
확인했습니다!!

**Comment by jaejin28** [comment]
이슈 클로즈 하겠습니다.
