### ISSUE TITLE
Django 서버 개발 PC 변경

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#39]
현재 Pycharm 내부에 Django 설치 과정 중, 충돌이 생겼는지 제 PC에 설치가 되지 않습니다.

괜찮으시다면 현재 모델 만드신 개발자분 PC로 진행해도 괜찮을까요..?

**Comment by jaejin28** [comment]
네

**Comment by rhdenro** [comment]
제 컴퓨터에서 작업 하셔도 상관 없습니다
