### ISSUE TITLE
최초 사용자 데이터 설정 방안

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#4]
현재 모델은 사용자가 사용 했던 좌석의 데이터와 현재 남은 좌석의 데이터를 비교해서 좌석을 추천해주는 모델인데 처음 도서관을 이용하는 사용자는 사용 했던 좌석의 데이터가 없기 때문에 비교가 불가능 합니다.
그래서 최초 사용자의 데이터를 어떤식으로 받을 것인지 논의가 필요합니다.

**Comment by BaekJae** [comment]
사용자가 제시 하여 주는 사전 정보(선호 판별 정보)를 기준으로 몇 가지의 좌석을 추천해 주고, 그에 따라 사람의 선호 취향을 정하는 것은 어떨까요?

**Comment by jaejin28** [comment]
@BaekJae 여기에 추가적으로 좌석 위치나 형태에 대한 기본적인 정보를 텍스트 혹은 사진으로 보여주면서 복수 선택에 도움을 주는 방법도 좋은거 같습니다.

**Comment by BaekJae** [comment]
@jaejin28 
괜찮은 것 같습니다.
