### ISSUE TITLE
좌석데이터에 수정

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#40]
좌석데이터의 일부가 추가로 조사한 결과와 불일치하는 부분이 있어 이를 변경해 주셨으면 합니다 변경데이터는 따로 전달하겠습니다

**Comment by BaekJae** [comment]
확인했고 DB 반영 준비하겠습니다.

**Comment by jaejin28** [comment]
넵!! 확인했습니다.

**Comment by jaejin28** [comment]
이슈 클로즈 하겠습니다.
