### ISSUE TITLE
우대인원 선호를 사용할 경우의 구현 요구

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#41]
우대인원은 일반 추천에서는 최대한 제외하는 방식으로 모델을 구현하려고 하니 우대인원은 별도의 기능으로 구현해 주시고 데이터를 보내실 때 판별할 수 있는 요소를 같이 보내주세요

**Comment by BaekJae** [comment]
확인했고 별도의 issue로 공지하겠습니다. 확인 부탁드립니다.

**Comment by jaejin28** [comment]
확인했습니다
