### ISSUE TITLE
모델 구현시 밀집도의 개념 변경

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#42]
원래는 좌석의 좌우를 기준으로 밀집도를 내려고 했으나 모든 좌석의 모양과 번호순번에 차이가 있어 구현자체가 매우 큰 소요가 필요하여 밀집도를 각 섹터의 인원수로 값을 내어 사용하려고 하는데
다른 의견있으시면 답변해 주세요

**Comment by BaekJae** [comment]
섹터의 구분자가 어떻게되나요?

**Comment by jaejin28** [comment]
없습니다. 확인했습니다!!

**Comment by jaejin28** [comment]
이슈 닫겠습니다.
