### ISSUE TITLE
좌석 추천 요청 규칙(Express to Django API Server)

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#43]
초기 Front에서 어떻게 받아 오는가에 따라 응답 및 Call 하는 함수의 차이가 있습니다.

주로 우대좌석을 사용하느냐 그렇지 않느냐에 따라 호출하는 함수의 차이가 존재합니다.

**우대좌석 사용 시 요청 Parameter**
user_id: 사용자의 아이디
isPrefer: 우대좌석 사용여부
person: 이용 명 수
isEdge: 가장자리 선호 여부

**우대좌석 비 사용 시 요청 Parameter**
user_id: 사용자의 아이디
isPc: PC 사용 여부
isConcent: 콘센트 사용 여부
isEdge: 가장자리 선호 여부

**요청 해주실 파라미터**는 아래와 같습니다.
statusCode: 상태코드(정상 완료시 200 리턴 부탁드리겠습니다!)
result: 결과 좌석

빠지거나 필요한 거 있으실 경우 추가 요청 댓글로 남겨주시고, Front-End 작업자 분은 위의 **작업 파라미터** 참고하여 요청 부탁드립니다.

**Comment by jaejin28** [comment]
네 확인했습니다.

**Comment by rhdenro** [comment]
확인 했습니다
