### ISSUE TITLE
Django서버 추가 작업

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#44]
Express 서버 내부의 밑작업이 종료된 상황입니다.

최근 무슨 이유인지 모르겠지만 다시 Django가 컴퓨터에서 정상 작동하여, Merge하여 Backend작업을 다시 진행하고자 합니다.

현재 진행 중인 **Feature_api-call branch와 Feature_modelserver branch를 병합**하고, 제 PC에서 통합 작업을 진행하고자 합니다.

확인 후 답변 부탁 드립니다.

**Comment by rhdenro** [comment]
확인 했고 병합도 완료했습니다

**Comment by jaejin28** [comment]
확인했습니다.

**Comment by jaejin28** [comment]
이슈 클로즈 하겠습니다!!
