### ISSUE TITLE
Front 작업 진행 정도

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#45]
branch 내부에서 작업 정도가 확인되지 않아 별도 문의 드립니다.

서버에서 자원을 드렸을 때 즉각적으로 반영 하실 수 있는지 문의 드립니다.

어느 정도 작업 완료하셨다고 하면 Forwarding된 IP와 포트 개인 메세지로 드리겠습니다.

**Comment by jaejin28** [comment]
네 따로 연락드리겠습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
