### ISSUE TITLE
Express - Django API 통신(이용자 선호 좌석)

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#46]
두 번째 통신 규약입니다.

제공되는 파라미터는 아래와 같습니다(요청 파라미터).
user_id: 학번
seatCode: 좌석 코드
rating: 별점
end_date: 종료 날짜(연-월-일)

결과 파라미터는 아래와 같이 규격을 맞춰주십시오.
statusCode: 결과코드(성공 시 200)

확인하고 추가 수정사항 있을시 Comment 부탁드립니다.

**Comment by rhdenro** [comment]
확인했고 오류코드는 406으로 return 하겠습니다

**Comment by jaejin28** [comment]
확인했습니다!!

**Comment by jaejin28** [comment]
이슈 닫겠습니당~~
