### ISSUE TITLE
로그인 기능 

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#48]
로그인 기능 구현 완료했습니다. 
commit 완료했습니다. 서버 쪽에서 확인 한번 부탁드립니다.

**Comment by BaekJae** [comment]
확인했습니다. sessionStorage 사용으로 확인되어 json형태로 자료만 전송하겠습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
