### ISSUE TITLE
메인페이지 기능

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#49]
메인페이지 기능에 해당하는 프레임 워크 작업 완료했습니다.
이 또한 commit 했으니 확인 한번 부탁드립니다.
메인페이지 같은 경우는 주요 기능을 추가해서 계속 commit 하도록 하겠습니다.

**Comment by BaekJae** [comment]
확인했습니다.

**Comment by rhdenro** [comment]
확인 했습니다
