### ISSUE TITLE
회원가입/로그인 시 필요한 정보

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#5]
사용자 회원가입과 로그인 시 어떠한 정보를 받아올 것인가에 대해 의견을 제시해주면 좋을거 같습니다.

각 학교의 도서관을 대상으로 하는 추천 시스템이므로
첫 번째로 이름과 학번을 통한 첫 번째 방법이 있고,
두 번째로 개인의 학교 이메일을 통한 방법도 괜찮을 거 같습니다.

추가 의견 있으면 말씀해 주세요

**Comment by BaekJae** [comment]
학교 이메일을 통한 방법으로 하자는 말씀이 이메일 인증을 사용하자는 말씀이실까요?

**Comment by rhdenro** [comment]
학생 데이터가 없는 상황이기 때문에 기본적인 회원가입에 이름과 학번만으로 구현을 하고 추후 데이터를 얻은 뒤 결정하는 게 맞는 것 같습니다.
서비스로 활용이 된다면 이메일 인증으로 해야하지만 현재는 배포 계획 등이 없기 때문에 후순위로 미뤄야 될 것 같습니다.

**Comment by jaejin28** [comment]
@BaekJae  네 맞습니다. 학교 이메일을 선택한 이유는 자신이 재학생이라는 인증에 있어 가장 확실한 방법이라고 생각했기 때문입니다. 다만 보안적인 문제를 생각했을 때 이름, 학번, 비밀번호를 추가로 입력하는 것도 생각중입니다.

**Comment by jaejin28** [comment]
@rhdenro 네 맞습니다. 사업적인 부분으로 들어간다면 앞서 답장한 것과 같이 보안적인 사항에 대해 철저한 인증을 해야겠지만,
말씀하신대로 배포 계획은 따로 없기 때문에 후순위로 미뤄서 간단하게 회원가입/로그인에 대한 방법만 생각하면 될거 같습니다.
