### ISSUE TITLE
이후 계획 공지 및 의견 수렴

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#51]
추천 모델은 완성이 되었고 서버도 오늘 내로 값을 전달 받는 것은 모두 완료할 예정입니다.
2차로 사용자의 선호좌석을 뽑아낼 데이터를 수정하는 기능은 12월 3일까지 모두 완료할 예정입니다
12월에 할 추가 작업이나 보완작업이 있다면 남겨주세요

**Comment by BaekJae** [comment]
**Readme 업데이트 작업**

**Front - back 연계 및 내용 표시 확인**

**최종 개선방안 및 한계점 결정**

이 정도 있을 것 같습니다.

**Comment by jaejin28** [comment]
확인했습니다.

**Comment by jaejin28** [comment]
이슈 닫겠습니다!!!
