### ISSUE TITLE
추천 개수 예외 처리 의견

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#52]
아침같은 좌석이 많이 비어있을 경우 비슷한 좌석이 많아 같은 선호코드를 공유하는 좌석은 3개이상 들어가지 않는 것으로 모델의 결과값을 수정하려고 하는데 의견 있으신가요?

**Comment by BaekJae** [comment]
그대로 진행하시면 될듯 합니다.

**Comment by jaejin28** [comment]
확인했습니다. 이슈는 클로즈 하겠습니다!!
