### ISSUE TITLE
사용자 선호좌석 변경 함수 구현 완료

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#56]
사용자 선호좌석 변경함수가 모두 구현이 되었습니다 노드에서 2차 연결 준비되면 알려주세요

**Comment by BaekJae** [comment]
확인했습니다. 준비되면 별도 issue로 말씀 드리겠습니다.

**Comment by jaejin28** [comment]
저도 확인했습니다ㅎㅎ
