### ISSUE TITLE
2차 통신시 정상적으로 이루어졌을 시 리턴 값

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#58]
2차 통신은 express서버에서 주는 값으로 DB만 변동시키는 작업인데 이 때 돌려줘야 하는 값이 따로 있나요?

**Comment by BaekJae** [comment]
Express 서버에서 정상 처리 결과를 확인하기 위해 return 값으로 코드같은 부분을 전달 해 주셨으면 합니다.

**Comment by jaejin28** [comment]
저도 확인했습니다.
