### ISSUE TITLE
추천 좌석 개수 수정 방안

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#6]
현재 초기 서비스 설계가 추천 좌석을 10개씩 3번에 걸쳐서 보여주는 형식이었는데 도서관 좌석이 300개 내외이고 도서관에 자리가 많이 남지 않은 경우 30개를 뽑게되면 모든 좌석을 다 보여주게 되어 추천이라는 서비스가 의미가 사라지는 경우가 생길 것으로 예상 되어 추천 좌석 개수를 초기 3개로 설정하고 거부시 다음 우선 순위가 있는 3개를 보여주는 방식으로 변경을 해야 될 필요가 있습니다

좌석 개수 조정
10개씩 3번 추천 -> 3개씩 2번 추천

**Comment by BaekJae** [comment]
한 번에 추천하는 좌석 개수를 추천 좌석 개수 / 2로 하는 것이 어떨까요?
만약 총 좌석 개수가 10개 이상이라면, 상위 10개의 항목을 5개씩 2번 추천하는 것도 괜찮을 것 같습니다.

**Comment by jaejin28** [comment]
@BaekJae 저도 총 10개 정도의 좌석 데이터를 뽑아놓고 5개씩 추천해주는게 좋다고 생각합니다. 
물론 3개든 5개든 비슷한 형태의 좌석이기 때문에 큰 의미가 없을 수 있지만 끝 쪽을 선호하는지 중앙을 선호하는지에 따른
취향 차이가 있을 수 있어 어느정도는 좌석을 제공해주는게 좋다고 생각합니다.

**Comment by rhdenro** [comment]
끝 쪽 선호 같은것도 라벨링 해서 직접 거르는 방식을 사용할 예정이라 고려되는 요소 대부분이 필터링 될 것이기 때문에 정확도를 위해 개수를 최소한으로 만드는 쪽으로 생각 중인데 도출된 좌석에 점수제를 넣어 기준점 이상의 것들을 /2해서 추천하는 방식으로 고려해 보겠습니다
