### ISSUE TITLE
좌석 코드 파싱 issue로 남겨놓겠습니다

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#62]
예시 1SA1

층
형태(S: 스마트, J: 조망형 P: Pc룸, N:노트북 전용)
각 층의 섹터
섹터별 좌석의 번호

이해 안되시는 것 있으면 남겨주세요

**Comment by BaekJae** [comment]
확인했습니다. 해당 내용 기반으로 좌석 코드 파서 Express에 제작하겠습니다.

**Comment by jaejin28** [comment]
확인했습니다. 이슈 닫겠습니다.
