### ISSUE TITLE
메인페이지 확정

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#64]
메인페이지의 기능으로 4가지를 선택하여 페이지 구현 완료하였습니다.
전체 좌석보기, 추천 받기, 연장하기 및 종료하기, 그리고 나의 이용기록 보기 페이지 입니다.
페이지 구현은 완료하였고 지난 commit 때 올린 코드에서 약간의 수정사항이 있어 내일 중으로 다시 commit 해서 올리겠습니다. 
혹여나 추가로 기능을 원하신다면 말씀해주세요.

**Comment by BaekJae** [comment]
로그아웃과 로그인 버튼같은 개인 신상정보 항목은 헤더부분에 바로가기로 있는게 더 편하지 않을까요?

**Comment by jaejin28** [comment]
네 그렇게 완료했습니다!!

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
