### ISSUE TITLE
메인페이지-전체좌석보기

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#65]
메인페이지 첫 번째 기능으로 전체 좌석보기 부분입니다.
전체 좌석보기는 현 충북대학교 도서관 모바일 어플리케이션의 좌석 배치도를 따올지,
웹 페이지의 도서관 도면을 가져올지, 아니면 좌석 형태에 맞게 새롭게 좌석 배치를 만들지 고민중에 있습니다. 이 부분에 대해 팀원 분들의 의견 공유 부탁드립니다.

**Comment by BaekJae** [comment]
도면을 가져오는 부분이 나을 것 같습니다.
가장 베스트인 부분은 좌석 배치를 만드는 부분이나, useState내부의 버그인지 정상적으로 state의 setting이 먹히질 않습니다.

**Comment by jaejin28** [comment]
확인했습니다!!

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
