### ISSUE TITLE
메인페이지-추천받기

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#66]
메인페이지의 두 번째 기능으로 추천받기 부분입니다.
저희 조가 가장 신경써서 만들고자 하는 부분으로 디자인적으로는 구현 완료했습니다.
이 부분은 내일 중으로 commit 하여 공유해드리겠습니다.

**Comment by BaekJae** [comment]
확인했습니다.

**Comment by rhdenro** [comment]
이슈 close하겠습니다
