### ISSUE TITLE
앱 구현 여부

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#7]
웹 기반으로 구현 계획을 잡았으나 수업시간 중의 질문이 있어 앱으로 구현하는 방식에 관해 논의하고 싶습니다.
물론 시간적 여유가 된다면 모바일 웹으로 구현하는 방안에 대해 논의 한 적이 있었지만 다른 의견 있다면 말씀해주세요.

**Comment by BaekJae** [comment]
아직은 해당 방안을 논의하기 너무 이른 시기라 생각됩니다.
우선 React Native를 이용하여 모바일 웹을 구성 한 후 논의해도 늦지 않을 것 같습니다.
그리고 기기들 간의 호환성을 고려할 때, 웹 기반 서비스가 더 나을 것으로 생각됩니다.

**Comment by rhdenro** [comment]
일단은 웹을 구성하고 모바일 웹을 추가로 구성하는 것이 프로젝트 기간에 맞는 방안이라고 생각하고 앱은 모바일 웹까지 구현이 끝나고 기간이 남는다면 구현하는 것이 맞다고 생각합니다.

**Comment by jaejin28** [comment]
네 확인했습니다.
