### ISSUE TITLE
메인페이지-연장하기 및 종료하기

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#70]
메인페이지의 연장하기 및 종료하기 기능입니다.
사용자는 이용하고 있는 현재 좌석에 대해 연장하기와 사용 종료하기를 선택할 수 있습니다.
이에 따라 연장하기 버튼을 클릭하면 팝업 형태로 2시간 연장을 진행하고,
종료하기 버튼을 클릭하면 "좌석 이용 종료" 라는 메시지와 함께 별점 평가하기 기능도 추가하였습니다. 1,2,3,4,5 점으로 선택할 수 있으며 제출하기 버튼을 구현해놓았기에 이를 누르면 사용자의 별점 평가 방식이 DB 로 저장될 수 있도록 구현 준비해놓겠습니다.

**Comment by BaekJae** [comment]
확인했습니다. 2시간이 맞나요?

**Comment by jaejin28** [comment]
2시간 맞습니다!!

**Comment by rhdenro** [comment]
확인했고 이슈 close 하겠습니다
