### ISSUE TITLE
메인페이지-나의 이용기록

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#71]
메인페이지의 나의 이용기록 부분입니다.
이 페이지를 클릭하면 사용자가 이전에 사용했던 좌석에 대한 정보(이전 사용 좌석 형태, 층 수, 좌석 번호, 이용 날짜, 평점)를 보여줍니다. 이를 통해 사용자는 자신이 받는 추천 리스트가 어떠한 좌석 데이터를 기반으로 이루어지고 있는지 확인할 수 있습니다.
하단에는 좌석 초기화 버튼을 구현해놓았는데 이 버튼을 클릭하면 자신의 이전 사용 좌석에 대한 모든 평점이 2점으로 바뀔 수 있게 요청 준비해놓겠습니다.

**Comment by BaekJae** [comment]
확인했습니다. Express도 이에 맞춰 구현하겠습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
