### ISSUE TITLE
페이지 별 필요 기능 구현 완료 및 이후 계획

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#72]
페이지 별로 필요 기능은 모두 구현 완료했습니다. 
내일 중으로 지금까지 한 부분을 모두 commit 하도록 하겠습니다. 
현재 백엔드와의 연동이 끝난 부분은 로그인/회원가입 부분,  우대인원/추가선택 부분, 조회하기 부분으로 
이후에는 별점 데이터 처리, 연장하기 처리, 좌석 초기화가 있을 것 같습니다.
추가로 필요한게 있으시면 말씀해주세요.

**Comment by BaekJae** [comment]
확인했습니다. 해당 경로 확장 준비하겠습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
