### ISSUE TITLE
React css 디자인

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#73]
css 기능은 페이지 별로 거의 대부분 완료 되었지만 지속적으로 수정할 필요가 있을 것 같습니다. 
혹시 원하는 색깔과 폰트 스타일, 폰트 사이즈 등이 있다면 말씀해주세요.
참고해서 스타일 작업 완료하겠습니다.

**Comment by BaekJae** [comment]
확인했습니다! 확실히 파스텔톤이 예쁜거같아요 ㅎㅎ

**Comment by jaejin28** [comment]
넹ㅎㅎㅎㅎㅎ

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
