### ISSUE TITLE
다중 좌석 선택 시 Express 내부 처리 오류

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#79]
좌석 내용이 String으로 받아지는지 정상적으로 map객체에 들어가지 않습니다.

혹시 가능하시다면 좌석 사이에 ','같은 특수문자를 넣어 요청을 보내주실 수 있으실까요?

**Comment by jaejin28** [comment]
확인했습니다!!!

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
