### ISSUE TITLE
모델 인공지능 사용 여부

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#8]
실제 좌석 데이터가 300개도 안되는 상황이기 때문에 굳이 인공지능을 사용 하지 않고 조건을 다중으로 설계해서 분류기를 직접 구현 하는 방법으로 개발 방향을 바꾸려고 하는데 어떻게 생각 하나요?

**Comment by BaekJae** [comment]
사실 AI가 데이터가 여러 개 있어야 라벨링도 용이하고, 학습의 결과도 정확하게 나오기 때문에 AI를 썼을 때 정확도가 높을지는 잘 모르겠습니다.
다중 분류기를 설계하여 정확도를 검토하는 방안이 더 나을 것 같습니다. 만약 정확도가 낮다면 그 때 여러 가지 방법을 시도해도 늦지 않다 생각됩니다.

**Comment by jaejin28** [comment]
네 좋습니다

**Comment by rhdenro** [comment]
그럼 분류기 구현으로 결정하겠습니다.
