### ISSUE TITLE
선점 좌석 확인 여부

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#80]
예약 진행 과정에서 React가 좌석 목록을 지속적으로 받아와 갱신하기는 어렵다고 판단했습니다.

그래서 예약 시 이미 예약되어 있는지를 확인하는 함수를 Express내부에 구현 했습니다.

확인 부탁드립니다.

**Comment by jaejin28** [comment]
확인했습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
