### ISSUE TITLE
Readme 작성 관련

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#81]
한 명이 취합하여 작성하는 방법을 고려했는데, 아무래도 각자가 진행한 부분은 각자 작성하는 것이 맞다 생각됩니다. 그래서 각자의 부분을 따로따로 작성하려 하는데, 이에 대한 이의가 있으신 분은 말씀해 주시기 바랍니다.

README.md 파일 작성 시 아래 부분들을 참고하여 주시기 바랍니다.

- 패키지 설치 방법
- 의존성
- OS와 Library의 버전 명시
- 사용 및 실행 방법
- 라이선스, 연락처

**Comment by jaejin28** [comment]
이의 없고 확인했습니다!!

**Comment by rhdenro** [comment]
확인했고 이슈 close 하겠습니다
