### ISSUE TITLE
예약 기록 초기화 경로 구현 관련

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#82]
예약 기록을 초기화하는 경로를 구현함에 있어 궁금증이 들어 질문드립니다.

예약 초기화를 진행하면, 본인이 가지고 있는 모든 기록의 평점을 초기화 하는 것인가요? 맞다면 해당 평점은 몇 정도로 초기화를 해야 하나요?

**Comment by jaejin28** [comment]
2점정도로 초기화를 진행하면 좋을거 같습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
