### ISSUE TITLE
2차 통신 시 밀집도에 관한 질문

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#83]
이전에 논의하셨을 때 밀집도를 2차 통신 당시 전달해 달라고 하셨는데, 그렇게 될 경우 별도의 State변수를 써서 저장해야 하는 문제가 생깁니다. 클라이언트단의 리소스를 더 차지하게 되어 좋은 방법이 아니라고 생각됩니다.

Express서버의 경우도 REST API구현의 특성 상 해당 수를 유지하기 매우 어려운데, 혹시 가능하시다면 종료 시점에서의 밀집도를 직접 계산하셔서 활용하실 수 있으실까요?

**Comment by jaejin28** [comment]
프론트 확인했습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
