### ISSUE TITLE
좌석 코드 파싱 규칙

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#84]
Express 서버 내부에서 좌석 Code를 파싱하여 전달함에 따라, 아래와 같은 규칙으로 사용해 주실 것을 권고드립니다.

좌석 코드의 경우 층, 좌석의 형태, 섹터, 좌석 번호의 정보를 가지고 있으며 이는 파싱하여 하나의 JSON배열로 전달됩니다.

실제 해당 내용을 사용할 시, axios 요청의 응답 값을 전달 받으시면 JSON배열을 받으실 수 있습니다.

다음은 내부 인자입니다.
floor: 층
form: 좌석의 형태
sector: 좌석의 섹터
seactorNum: 좌석 번호

**Comment by jaejin28** [comment]
해당 내부 규칙 확인했습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
