### ISSUE TITLE
서버 내부에서 예약 테스트를 진행할 시 조심하셔야 하는 부분

### ISSUE THREAD

**Issue by BaekJae** [rhdenro/jinddoback2#85]
최근 reservation이나 reservation_con 등 예약과 관련된 경로의 접근이 활발하게 확인되고 있습니다.

그러나 정상적으로 응답을 진행하지 못하는 경우들이 발생하는데, 대표적인 경우가 요청이 정상적으로 도달하지 않아 예약 취소 경로에서 500번 에러가 발생하는 경우입니다.

이는 주로 Front단에서 통신하다가 다른 요청이 먼저 실행되어 예약 요청이 정상 처리되지 않은 부분으로 보여, 해당 오류코드에 대한 예외 처리가 필요할 것 같습니다.

**Comment by BaekJae** [comment]
또, 응답값이 정상적으로 도착하지 못했더라도 DB의 예약값은 변경되었을 수 있습니다. 이점 유의하셔서 테스트 부탁드립니다.

**Comment by jaejin28** [comment]
확인했습니다. 테스트 진행할 시 말씀드리겠습니다.

**Comment by rhdenro** [comment]
이슈 close 하겠습니다
