### ISSUE TITLE
나의 이용기록 페이지 종료하기 - 별점 데이터 처리

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#86]
나의 이용 기록에서 종료하기 버튼을 클릭하면 별점 데이터를 사용자로부터 입력받을 수 있고 이 데이터를 서버에 전송하여 db에 저장되는 것까지 완료했습니다. 
혹시나 이상이 있다면 말씀해주세요.

**Comment by rhdenro** [comment]
확인 했습니다

**Comment by BaekJae** [comment]
확인했고 Issue Close 하겠습니다.
