### ISSUE TITLE
추천받기 - 좌석초기화

### ISSUE THREAD

**Issue by jaejin28** [rhdenro/jinddoback2#88]
시스템 상으로 추천 받는 좌석들이 마음에 들지 않을 경우 좌석 초기화 버튼을 클릭하여 기존의 좌석 데이터는 남아있도록 하지만 해당 좌석의 모든 별점 데이터를 2점으로 초기화 하는 작업 완료했습니다.

**Comment by rhdenro** [comment]
확인 했습니다

**Comment by BaekJae** [comment]
확인했고 Issue Close 하겠습니다.
