### ISSUE TITLE
최초 데이터 내부 요소

### ISSUE THREAD

**Issue by rhdenro** [rhdenro/jinddoback2#9]
현재 좌석 데이터 내부 요소로
숫자는 중요도
좌석 번호
사용 여부-1
콘센트 유무-2
pc 유무-2
정의된 자리별 형태-3
밀집도-3(추가적 고려 사항)
층수-3
가장자리 여부-3
등 정도로 구상을 하고 있는데 더 추가했으면 하거나 필요없을 것 같은 항목에 대해서 남겨주시면 반영해서
데이터 내부 요소 정하고 데이터 구축 하겠습니다.

**Comment by BaekJae** [comment]
데이터 자체는 괜찮은데, 좌석 번호를 H10과 같은 형식으로 입력받아 주셨으면 합니다.
또, 층 수의 경우에는 어차피 좌석 식별번호로 구분되기에 큰 상관 없을 것 같습니다.

**Comment by rhdenro** [comment]
엑셀에서 데이터 구축할 때 고려해서 층수는 삭제하고 좌석번호는 형식을 맞추고
층수는 모델 설계 때 따로 번호에서 추출하는 방식으로 구현 하겠습니다

**Comment by jaejin28** [comment]
네 확인했습니다.
